real_quiz/apps/campaign/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.SiteIndexView.as_view(),
        name="home"
    ),
    url(
        regex=r'^(?P<label>[\w-]{,50})/$',
        view=views.NewGameView.as_view(),
        name='new_game'
    ),
]

real_quiz/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('campaign.urls', namespace="campaign")),
    url(r'^admin/', admin.site.urls),
]

real_quiz/apps/campaign/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class Room(models.Model):
    name = models.TextField()
    label = models.SlugField(unique=True)

    def __unicode__(self):
        return self.label

class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages')
    handle = models.TextField()
    message = models.TextField()
    timestamp = models.DateTimeField(default=timezone.now, db_index=True)

    def __unicode__(self):
        return '[{timestamp}] {handle}: {message}'.format(**self.as_dict())

    @property
    def formatted_timestamp(self):
        return self.timestamp.strftime('%b %-d %-I:%M %p')

    def as_dict(self):
        return {'handle': self.handle, 'message': self.message, 'timestamp': self.formatted_timestamp}

real_quiz/apps/campaign/views.py
import haikunator
from django.shortcuts import render
from django.db import transaction
from django.views.generic import (
    TemplateView,
)

from .models import Room


class SiteIndexView(TemplateView):
    """
    Default Site Index
    """
    template_name = "campaign/home.html"

    def get_context_data(self, **kwargs):
        context = super(SiteIndexView, self).get_context_data(**kwargs)
        new_room = None
        while not new_room:
            with transaction.atomic():
                label = haikunator.haikunate()
                if Room.objects.filter(label=label).exists():
                    continue
                new_room = Room.objects.create(label=label)
                context['label'] = label
        return context


class NewGameView(TemplateView):
    """
    Default Site Index
    """
    template_name = "campaign/new-game.html"

    def get_context_data(self, **kwargs):
        context = super(NewGameView, self).get_context_data(**kwargs)
        room, created = Room.objects.get_or_create(label=kwargs.get('label'))
        messages = reversed(room.messages.order_by('-timestamp')[:50])
        context['room'] = room
        context['messages'] = messages

        return context

real_quiz/templates/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta name="description" content="{% block description %}{% endblock %}" />
    <meta name="keywords" content="{% block keywords %}{% endblock %}" />
    <meta name="viewport" content="{% block viewport %}width=device-width"{% endblock %}>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>{% block title %}real_quiz{% endblock title %}</title>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <link rel="icon" type="image/gif" href="{% static 'img/favicon.gif' %}">

    {% block css %}
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/skeleton.css' %}">
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">
    {% endblock %}

  </head>

  <body>
    <div class="container">

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <script src="{% static 'js/scripts.js' %}"></script>
    {% endblock javascript %}
    {% block extra_js %}
    {% endblock extra_js %}

  </body>
</html>

real_quiz/templates/campaign/home.html
{% extends "base.html" %}

{% block content %}
  <h1>Start Game</h1>
  <p>
    <a class="button button-primary" href="{% url 'campaign:new_game' label=label %}">Generate Game Pin</a>
  </p>
{% endblock content %}

real_quiz/templates/campaign/new-game.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}
<h1>{{ room.label }}</h1>
<p>
    <label for="handle">Your name:</label>
    <input id="handle" type="text" placeholder="handle">
</p>
<form id="chatform">
    <table id="chat">
        <tbody>
            {% for message in messages %}
                <tr>
                    <td>{{ message.formatted_timestamp }}</td>
                    <td>{{ message.handle }}</td>
                    <td>{{ message.message }}</td>
                </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td>Say something:</td>
                <td colspan=2>
                    <input id="message" type="text" placeholder="message">
                    <button type="submit" id="go">Say it</button>
                </td>
            </tr>
        </tfoot>
    </table>
</form>
{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src='{% static "js/jquery-1.12.1.min.js" %}'></script>
<script type="text/javascript" src='{% static "js/reconnecting-websocket.min.js" %}'></script>
<script type="text/javascript" src='{% static "js/chat.js" %}'></script>
{% endblock extra_js %}